# Generated by Django 4.1.1 on 2022-09-08 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instargram', '0002_rename_massage_post_content'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='content',
            new_name='message',
        ),
    ]
