# Generated by Django 4.1.1 on 2022-09-08 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instargram', '0003_rename_content_post_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_public',
            field=models.BooleanField(default=False, verbose_name='공개여부'),
        ),
    ]
